# Generated by Django 5.1.1 on 2025-02-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMTReports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='labtimeline',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='stage_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='RMTReports.imp_rmtrrequest'),
        ),
        migrations.AlterField(
            model_name='imp_rmtrrequest',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imp_rmtrrequest',
            name='material_name',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='imp_rmtrrequest',
            name='specs',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='imp_rmtrrequest',
            name='tests',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='rmtrrequest',
            name='material_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rmtrrequest',
            name='requested_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rmtrrequest',
            name='specs',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='rmtrrequest',
            name='tests',
            field=models.CharField(blank=True, max_length=1000),
        ),
        
    ]


