# Generated by Django 5.1.1 on 2025-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMTReports', '0002_imp_rmtrrequest_labtimeline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impdocumentattachment',
            options={},
        ),
        migrations.RemoveField(
            model_name='impdocumentattachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='impdocumentattachment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='impdocumentattachment',
            name='report',
        ),
        migrations.RemoveField(
            model_name='impdocumentattachment',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='impdocumentattachment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
