from django.urls import path
from .views import (
    test_request, test, pending_reports, final_report, dashboard,check_rmtr,
    pdf_report, approval_page, pending, all_rmtr, my_rmtr, generate_rmtr_number, 
    home_view, get_suppliers, manage_suppliers, login_view, fill_page, process_approval,imp_completed_reports,
    submit_form, completed_reports, create_report, test_view, create_rmtr_request,
    create_supplier, upload_rmtr_image, plant_hod_data, check_pending_rmtrs,retest_request,imp_pending,
    fetch_material_data, hod_approval,logout_view,get_rmtr_tests,get_rmtr_report,edit_rmtr,imp_test_request,generate_imp_rmtr_number,
    hod_purchase_approval, hod_test_approval,get_target_route, fm_approval, fm_test_approval,management_approval_2,
    management_approval, management_test_approval, milan_approval,  qao_test_approval,get_report_data,download_rmtr_pdf, download_rmtr_comments_text,
    imp_hod_purchase_approval,edit_imp_rmtr,imp_management_approval,imp_management_approval_2,imp_fm_approval, imp_hod_approval,imp_fill_page,imp_qao_test_approval,imp_rmtr_tests,imp_retest_request,
    imp_hod_test_approval, imp_fm_test_approval,imp_management_test_approval,imp_milan_approval,get_rmtr_comments,download_rmtr_comments,
    imp_download_rmtr_pdf,imp_check_rmtr,imp_export_to_excel,imp_get_report_data, imp_get_rmtr_report, imp_get_rmtr_tests, imp_process_test_results,preview_rmtr_pdf,imp_all_rmtrs,
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', login_view, name='login'),
    path('', login_view, name='home'),  

    path('dashboard/', dashboard, name='dashboard'),
    path('test_request/', test_request, name='test_request'),  
    path('test-request/', test_request, name='test_request'), 
    path('submit_form/', submit_form, name='submit_form'),
    path('test_request/<str:rmtr_no>/', test_request, name='test_request_with_id'),
    path('test/', test_view, name='test'),
    path('fill-page/<str:rmtr_no>/', fill_page, name='fill_page'),
    path('fill_page/<pk>', fill_page, name='fill_page'),  
    path('get-target-route', get_target_route, name='get_target_route'),
    path('pending/', pending_reports, name='pending'),
    path('pending_reports/', pending_reports, name='pending_reports'),  
    path('completed_reports/', completed_reports, name='completed_reports'),
   
    path('all_rmtr/', all_rmtr, name='all_rmtr'),
    path('imp_all_rmtrs/', imp_all_rmtrs, name='imp_all_rmtrs'),
    path('my_rmtr/', my_rmtr, name='my_rmtr'),
    path('final_report/', final_report, name='final_report'),
    path('approval/<str:rmtr_no>/hod-purchase/', hod_purchase_approval, name='hod_purchase_approval'),
    path('approval/<str:rmtr_no>/', process_approval, name='process_approval'),
    path('edit_rmtr/<str:rmtr_no>/', edit_rmtr, name='edit_rmtr'),
    path('approval_page/', approval_page, name='approval_page'),
    path('approval_page/<int:rmtr_no>/', approval_page, name='approval_page_with_id'),
    path('hod_purchase_approval/<str:rmtr_no>/', hod_purchase_approval, name='hod_purchase_approval'),
    path('fm_approval/', fm_approval, name='fm_approval'),
    path('management_approval/', management_approval, name='management_approval'),
    path('hod_approval/', hod_approval, name='hod_approval'),
    path('hod_test_approval/', hod_test_approval, name='hod_test_approval'),
    path('fm_test_approval/', fm_test_approval, name='fm_test_approval'),
    path('management_test_approval/', management_test_approval, name='management_test_approval'),
    path('qao_test_approval/', qao_test_approval, name='qao_test_approval'),
    path('hod_purchase_approval/<str:rmtr_no>/', hod_purchase_approval, name='hod_purchase_approval'),
    path('management_approval/<str:rmtr_no>/', management_approval, name='management_approval'),
    path('retest_request/<str:rmtr_no>/', retest_request, name='retest_request'),
    path('fm_approval/<str:rmtr_no>/', fm_approval, name='fm_approval'),
    path('hod_approval/<str:rmtr_no>/', hod_approval, name='hod_approval'),
    path('fill_page/<str:rmtr_no>/', fill_page, name='fill_page'),
    path('qao_test_approval/<str:rmtr_no>/', qao_test_approval, name='qao_test_approval'),
    path('hod_test_approval/<str:rmtr_no>/', hod_test_approval, name='hod_test_approval'),
    path('fm_test_approval/<str:rmtr_no>/', fm_test_approval, name='fm_test_approval'),
    path('management_test_approval/<str:rmtr_no>/', management_test_approval, name='management_test_approval'),
    path('management_approval_2/<str:rmtr_no>/', management_approval_2, name='management_approval_2'),
    
    # API Endpoints
    path('rmtr/<str:rmtr_no>/tests/', get_rmtr_tests, name='get_rmtr_tests'),
    path('api/rmtr-reports/<str:rmtr_no>/', get_rmtr_report, name='get_rmtr_report'),
    path('completed_reports/', completed_reports, name='completed_reports'),
    path('rmtr/<str:rmtr_no>/tests/', get_rmtr_tests, name='get_rmtr_tests'),
    path('api/rmtr-reports/<str:rmtr_no>/', get_rmtr_report, name='get_rmtr_report'),
    path('generate-rmtr-number/', generate_rmtr_number, name='generate_rmtr_number'),
    path('api/suppliers/', get_suppliers, name='get_suppliers'),
    path('get-plant-hod-data/', plant_hod_data, name='plant_hod_data'),
    path('fetch-material-data/', fetch_material_data, name='fetch_material_data'),
    path('api/rmtr-reports/<str:rmtr_no>/', get_report_data, name='get_report_data'),
    path('check-pending-rmtrs/', check_pending_rmtrs, name='check_pending_rmtrs'),
    path('get-target-route/', get_target_route, name='get_target_route'),
    path('test/', test_view, name='test'),
    path('test/<str:rmtr_no>/', test_request, name='test_request'),
    path('rmtr/<str:rmtr_id>/tests/', get_rmtr_tests, name='get_rmtr_tests'),
    path('api/rmtr-reports/<str:rmtr_no>/', get_rmtr_report, name='get_rmtr_report'),
    path('rmtr/<int:rmtr_id>/tests/', get_rmtr_tests, name='rmtr_tests'),
    path('submit-form/', submit_form, name='submit_form'),
    path('create_report/', create_report, name='create_report'),
    path('upload/', upload_rmtr_image, name='upload_rmtr_image'),
    path('logout/', logout_view, name='logout'),
    path('manage-suppliers/', manage_suppliers, name='manage_suppliers'),
    path('suppliers/', manage_suppliers, name='manage_suppliers'),
    path('create-supplier/', create_supplier, name='create_supplier'),
    path('milan_approval/<str:rmtr_no>/', milan_approval, name='milan_approval'), 
    path('api/report/<str:rmtr_no>/',get_report_data, name='get_report_data'),
    path('pdf_report/', pdf_report, name='pdf_report'),
    path('fill_page/<str:rmtr_no>/', fill_page, name='fill_page'),
    path('rmtr/<str:rmtr_no>/download/', download_rmtr_pdf, name='download_rmtr_pdf'),
    path('api/check-rmtr/<str:rmtr_no>/', check_rmtr, name='check_rmtr'),
    path('check_rmtr', check_rmtr, name='check_rmtr'),
    
    # COMMENTS ENDPOINTS - ADD THESE LINES
    path('rmtr/<str:rmtr_no>/comments/', get_rmtr_comments, name='get_rmtr_comments'),
    path('rmtr/<str:rmtr_no>/comments/download/', download_rmtr_comments, name='download_rmtr_comments'),
    path('rmtr/<str:rmtr_no>/comments/download/text/', download_rmtr_comments_text, name='download_rmtr_comments_text'),
    
    # IMPORTS ENDPOINTS
    path('imp_test_request/<str:imp_rmtr_no>/', imp_test_request, name='imp_test_request'),
    path('imp_test_request/', imp_test_request, name='imp_test_request'),
    path('generate-imp-rmtr-number/', generate_imp_rmtr_number, name='generate_imp_rmtr_number'),
    path('imp_test_request/', imp_test_request, name='imp_test_request'),
    path('imp_pending/', imp_pending, name='imp_pending'),
    path('imp_completed_reports/', imp_completed_reports, name='imp_completed_reports'),
    path('imp_hod_purchase_approval/<str:imp_rmtr_no>/', imp_hod_purchase_approval, name='imp_hod_purchase_approval'),
    path('edit_imp_rmtr/<str:imp_rmtr_no>/', edit_imp_rmtr, name='edit_imp_rmtr'),
    path('imp_management_approval/<str:imp_rmtr_no>/', imp_management_approval, name= 'imp_management_approval'),
    path('imp_management_approval_2/<str:imp_rmtr_no>/', imp_management_approval_2, name= 'imp_management_approval_2'),
    path('imp_fm_approval/<str:imp_rmtr_no>/', imp_fm_approval, name='imp_fm_approval'), 
    path('imp_hod_approval/<str:imp_rmtr_no>/', imp_hod_approval, name='imp_hod_approval'),  
    path('imp_fill_page/<str:imp_rmtr_no>/', imp_fill_page, name='imp_fill_page'),
    path('imp_qao_test_approval/<str:imp_rmtr_no>/', imp_qao_test_approval, name='imp_qao_test_approval'),
    path('imp_rmtr/<str:imp_rmtr_no>/tests/', imp_rmtr_tests, name='imp_rmtr_tests'),
    path('imp_retest_request/<str:imp_rmtr_no>/', imp_retest_request, name='imp_retest_request'),
    path('imp_hod_test_approval/<str:imp_rmtr_no>/', imp_hod_test_approval, name ='imp_hod_test_approval'),
    path('imp_fm_test_approval/<str:imp_rmtr_no>/', imp_fm_test_approval, name ='imp_fm_test_approval'),
    path('imp_management_test_approval/<str:imp_rmtr_no>/', imp_management_test_approval, name ='imp_management_test_approval'),
    path('imp_milan_approval/<str:imp_rmtr_no>/',imp_milan_approval, name='imp_milan_approval'),
    path('imp_completed_reports/', imp_completed_reports, name='imp_completed_reports'),
    path('imp_export_to_excel/', imp_export_to_excel, name='imp_export_to_excel'),
    path('imp_rmtr/<str:imp_rmtr_no>/download/', imp_download_rmtr_pdf, name='imp_download_rmtr_pdf'),
    path('imp_report_data/<str:imp_rmtr_no>/', imp_get_report_data, name='imp_report_data'),
    path('imp_rmtr_tests/<str:imp_rmtr_no>/', imp_get_rmtr_tests, name='imp_rmtr_tests'),
    path('imp_rmtr_report/<str:imp_rmtr_no>/', imp_get_rmtr_report, name='imp_rmtr_report'),
    path('imp_check_rmtr/<str:imp_rmtr_no>/', imp_check_rmtr, name='imp_check_rmtr'),
    path('api/report/<str:imp_rmtr_no>/',imp_get_report_data, name='imp_get_report_data'),
    path('imp-rmtr/<str:imp_rmtr_no>/tests/', imp_get_rmtr_tests, name='imp_get_rmtr_tests'),
    path('rmtr/<str:rmtr_no>/download/', download_rmtr_pdf, name='download_rmtr_pdf'),
    path('rmtr/<str:rmtr_no>/tests/', get_rmtr_tests, name='get_rmtr_tests'),
    path('rmtr/<str:rmtr_no>/tests/', get_rmtr_tests, name='get_rmtr_tests'),
    path('imp-rmtr/<str:rmtr_no>/download/', download_rmtr_pdf, name='imp_download_rmtr_pdf'),
    path('imp-completed-reports/', imp_completed_reports, name='imp_completed_reports'),
    path('imp-rmtr/<str:rmtr_no>/tests/', imp_get_rmtr_tests, name='imp_get_rmtr_tests'),
    path('imp-rmtr/<str:rmtr_no>/download/', imp_download_rmtr_pdf, name='imp_download_rmtr_pdf'),
    path('imp-rmtr/<str:rmtr_no>/data/', imp_get_report_data, name='imp_get_report_data'),
    path('rmtr/imp/<str:rmtr_no>/tests/', imp_get_rmtr_tests, name='imp_rmtr_tests_alt'),
    path('rmtr/imp/<str:rmtr_no>/download/', imp_download_rmtr_pdf, name='imp_rmtr_download_alt'),
    path('rmtr/imp/<str:rmtr_no>/preview/', imp_download_rmtr_pdf, name='imp_rmtr_preview_alt'),
    path('imp-rmtr/<str:rmtr_no>/preview/', preview_rmtr_pdf, name='preview_rmtr_pdf'),
    path('rmtr/<str:rmtr_no>/comments/', get_rmtr_comments, name='get_rmtr_comments'),
    path('api/rmtr/<str:rmtr_no>/comments/', get_rmtr_comments, name='api_get_rmtr_comments'),
    path('imp/rmtr/<str:imp_rmtr_no>/comments/', get_rmtr_comments, name='get_imp_rmtr_comments'),
    path('api/imp/rmtr/<str:imp_rmtr_no>/comments/', get_rmtr_comments, name='api_get_imp_rmtr_comments'),
]   

# Serve media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)