# Generated by Django 4.1 on 2025-02-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RMTReports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imp_rmtrrequest",
            name="labtimeline",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="rmtrrequest",
            name="labtimeline",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
