# Generated by Django 5.0.6 on 2025-08-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMTReports', '0002_alter_imp_rmtrrequest_labtimeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmtrrequest',
            name='kapa_standards17',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='raw_material_results17',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='sample_results17',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='tests_carried_out17',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
