# Generated by Django 5.0.6 on 2025-08-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMTReports', '0003_rmtrrequest_kapa_standards17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmtrrequest',
            name='kapa_standards18',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='kapa_standards19',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='kapa_standards20',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='raw_material_results18',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='raw_material_results19',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='raw_material_results20',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='sample_results18',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='sample_results19',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='sample_results20',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='tests_carried_out18',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='tests_carried_out19',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='tests_carried_out20',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
