# Generated by Django 5.0.6 on 2025-08-07 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMTReports', '0005_imp_rmtrrequest_kapa_standards17_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvallog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='kapa_standards17',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='kapa_standards18',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='kapa_standards19',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='kapa_standards20',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='raw_material_results17',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='raw_material_results18',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='raw_material_results19',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='raw_material_results20',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='sample_results17',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='sample_results18',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='sample_results19',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='sample_results20',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='tests_carried_out17',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='tests_carried_out18',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='tests_carried_out19',
        ),
        migrations.RemoveField(
            model_name='imp_rmtrrequest',
            name='tests_carried_out20',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='kapa_standards17',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='kapa_standards18',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='kapa_standards19',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='kapa_standards20',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='raw_material_results17',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='raw_material_results18',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='raw_material_results19',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='raw_material_results20',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='sample_results17',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='sample_results18',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='sample_results19',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='sample_results20',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='tests_carried_out17',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='tests_carried_out18',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='tests_carried_out19',
        ),
        migrations.RemoveField(
            model_name='rmtrrequest',
            name='tests_carried_out20',
        ),
        migrations.AddField(
            model_name='approvallog',
            name='approval_stage',
            field=models.CharField(blank=True, help_text='Which approval stage (hod_purchase, management, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='field_changes',
            field=models.JSONField(default=dict, help_text='Track specific field changes'),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='status_after',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='status_before',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='fm_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='fm_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_fm_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='fm_test_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='fm_test_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_fm_test_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='hod_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='hod_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_hod_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='hod_purchase_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='hod_purchase_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_hod_purchase_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='hod_test_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='hod_test_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_hod_test_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='last_status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made the last status change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_last_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='management_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='management_modified_at_2',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='management_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_management_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='management_modified_by_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_management_modifications_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='management_test_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='management_test_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_management_test_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='milan_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='milan_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_milan_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='qao_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='qao_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_qao_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='test_results_modified_at',
            field=models.DateTimeField(blank=True, help_text='When test results were last modified', null=True),
        ),
        migrations.AddField(
            model_name='imp_rmtrrequest',
            name='test_results_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_test_result_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='fm_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='fm_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_fm_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='fm_test_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='fm_test_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_fm_test_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='hod_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='hod_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_hod_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='hod_purchase_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='hod_purchase_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_hod_purchase_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='hod_test_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='hod_test_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_hod_test_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='last_status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made the last status change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_last_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='management_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='management_modified_at_2',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='management_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_management_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='management_modified_by_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_management_modifications_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='management_test_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='management_test_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_management_test_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='milan_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='milan_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_milan_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='qao_modified_at',
            field=models.DateTimeField(blank=True, help_text='When this approval was last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='qao_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_qao_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='test_results_modified_at',
            field=models.DateTimeField(blank=True, help_text='When test results were last modified', null=True),
        ),
        migrations.AddField(
            model_name='rmtrrequest',
            name='test_results_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_test_result_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('retest_requested', 'Retest Requested'), ('retest_completed', 'Retest Completed'), ('edited', 'Report Edited'), ('status_changed', 'Status Changed'), ('test_results_updated', 'Test Results Updated'), ('created', 'Created')], max_length=30),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imp_rmtrrequest',
            name='labtimeline',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmtrrequest',
            name='hod_purchase_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_hod_purchase_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rmtrrequest',
            name='labtimeline',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmtrrequest',
            name='management_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_management_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rmtrrequest',
            name='management_by_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmtr_management_approvals_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['report', '-created_at'], name='RMTReports__report__4a2b63_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['user', '-created_at'], name='RMTReports__user_id_57b93b_idx'),
        ),
    ]
