# Generated by Django 5.2 on 2026-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_artworkrequest_product_name_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcolorspec',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
